FROM python:3.8

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 5000

VOLUME [ "/data" ]

ENV MAPS_API_KEY='SetViaEnvFile'
ENV FLASK_DEBUG=1

CMD ["python", "app.py"]
